/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Request {
  'id' : string,
  'customerName' : string,
  'status' : RequestStatus,
  'updatedTime' : bigint,
  'user' : Principal,
  'description' : string,
  'createdTime' : bigint,
  'address' : string,
  'sparesUsed' : [] | [string],
  'category' : string,
  'phoneNumber' : string,
  'requestType' : RequestType,
  'assignedTechnician' : [] | [string],
}
export type RequestStatus = { 'closed' : null } |
  { 'open' : null };
export type RequestType = { 'service' : null } |
  { 'spares' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminUpdateRequest' : ActorMethod<
    [string, [] | [RequestStatus], [] | [string], [] | [string]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTechnician' : ActorMethod<[string, string], undefined>,
  'createRequest' : ActorMethod<
    [string, string, RequestType, string, string, string, string],
    undefined
  >,
  'getAllRequests' : ActorMethod<[], Array<Request>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRequestById' : ActorMethod<[string], [] | [Request]>,
  'getRequestsByCaller' : ActorMethod<[], Array<Request>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRequestStatus' : ActorMethod<[string, RequestStatus], undefined>,
  'updateSparesUsed' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];