/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Brand = IDL.Variant({
  'lg' : IDL.Null,
  'daikin' : IDL.Null,
  'other' : IDL.Text,
  'voltas' : IDL.Null,
  'whirlpool' : IDL.Null,
  'samsung' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'service' : IDL.Null,
  'spares' : IDL.Null,
});
export const Technician = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Feedback = IDL.Record({
  'customerName' : IDL.Text,
  'technician' : IDL.Opt(IDL.Text),
  'createdTime' : IDL.Nat64,
  'ticketId' : IDL.Text,
  'rating' : IDL.Nat,
  'comments' : IDL.Opt(IDL.Text),
});
export const RequestStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'pendingSpares' : IDL.Null,
  'enRoute' : IDL.Null,
});
export const Request = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : RequestStatus,
  'updatedTime' : IDL.Nat64,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'createdTime' : IDL.Nat64,
  'address' : IDL.Text,
  'sparesUsed' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'brand' : Brand,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Text,
  'requestType' : RequestType,
  'assignedTechnician' : IDL.Opt(IDL.Text),
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'updatedTime' : IDL.Nat64,
  'threshold' : IDL.Nat,
  'name' : IDL.Text,
  'createdTime' : IDL.Nat64,
  'quantity' : IDL.Nat,
});
export const InventoryLog = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'technician' : IDL.Text,
  'createdTime' : IDL.Nat64,
  'ticketId' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'addInventoryLog' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addTechnician' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTechnician' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createRequest' : IDL.Func(
      [
        IDL.Text,
        Brand,
        IDL.Text,
        RequestType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAllTechnicians' : IDL.Func([], [IDL.Vec(Technician)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeedbackByTechnician' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Feedback)],
      ['query'],
    ),
  'getFilteredRequests' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(Brand),
        IDL.Opt(IDL.Text),
        IDL.Opt(RequestStatus),
      ],
      [IDL.Vec(Request)],
      ['query'],
    ),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getInventoryLogs' : IDL.Func([], [IDL.Vec(InventoryLog)], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getRequestById' : IDL.Func([IDL.Text], [IDL.Opt(Request)], ['query']),
  'getRequestsByCaller' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getTechnicianPerformance' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'trackStatusById' : IDL.Func([IDL.Text], [IDL.Opt(Request)], ['query']),
  'trackStatusByIdAndPhone' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Request)],
      ['query'],
    ),
  'updateInventoryItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Brand = IDL.Variant({
    'lg' : IDL.Null,
    'daikin' : IDL.Null,
    'other' : IDL.Text,
    'voltas' : IDL.Null,
    'whirlpool' : IDL.Null,
    'samsung' : IDL.Null,
  });
  const RequestType = IDL.Variant({
    'service' : IDL.Null,
    'spares' : IDL.Null,
  });
  const Technician = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Feedback = IDL.Record({
    'customerName' : IDL.Text,
    'technician' : IDL.Opt(IDL.Text),
    'createdTime' : IDL.Nat64,
    'ticketId' : IDL.Text,
    'rating' : IDL.Nat,
    'comments' : IDL.Opt(IDL.Text),
  });
  const RequestStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'pendingSpares' : IDL.Null,
    'enRoute' : IDL.Null,
  });
  const Request = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : RequestStatus,
    'updatedTime' : IDL.Nat64,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'createdTime' : IDL.Nat64,
    'address' : IDL.Text,
    'sparesUsed' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'brand' : Brand,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Text,
    'requestType' : RequestType,
    'assignedTechnician' : IDL.Opt(IDL.Text),
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'updatedTime' : IDL.Nat64,
    'threshold' : IDL.Nat,
    'name' : IDL.Text,
    'createdTime' : IDL.Nat64,
    'quantity' : IDL.Nat,
  });
  const InventoryLog = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'technician' : IDL.Text,
    'createdTime' : IDL.Nat64,
    'ticketId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addInventoryLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addTechnician' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTechnician' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createRequest' : IDL.Func(
        [
          IDL.Text,
          Brand,
          IDL.Text,
          RequestType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllTechnicians' : IDL.Func([], [IDL.Vec(Technician)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeedbackByTechnician' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getFilteredRequests' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(Brand),
          IDL.Opt(IDL.Text),
          IDL.Opt(RequestStatus),
        ],
        [IDL.Vec(Request)],
        ['query'],
      ),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getInventoryLogs' : IDL.Func([], [IDL.Vec(InventoryLog)], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getRequestById' : IDL.Func([IDL.Text], [IDL.Opt(Request)], ['query']),
    'getRequestsByCaller' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getTechnicianPerformance' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'trackStatusById' : IDL.Func([IDL.Text], [IDL.Opt(Request)], ['query']),
    'trackStatusByIdAndPhone' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Request)],
        ['query'],
      ),
    'updateInventoryItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };