/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequestStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'service' : IDL.Null,
  'spares' : IDL.Null,
});
export const Request = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : RequestStatus,
  'updatedTime' : IDL.Nat64,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'createdTime' : IDL.Nat64,
  'address' : IDL.Text,
  'sparesUsed' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'requestType' : RequestType,
  'assignedTechnician' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminUpdateRequest' : IDL.Func(
      [IDL.Text, IDL.Opt(RequestStatus), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTechnician' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createRequest' : IDL.Func(
      [IDL.Text, IDL.Text, RequestType, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRequestById' : IDL.Func([IDL.Text], [IDL.Opt(Request)], ['query']),
  'getRequestsByCaller' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Text, RequestStatus], [], []),
  'updateSparesUsed' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequestStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestType = IDL.Variant({
    'service' : IDL.Null,
    'spares' : IDL.Null,
  });
  const Request = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : RequestStatus,
    'updatedTime' : IDL.Nat64,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'createdTime' : IDL.Nat64,
    'address' : IDL.Text,
    'sparesUsed' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'requestType' : RequestType,
    'assignedTechnician' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminUpdateRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(RequestStatus),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTechnician' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          RequestType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRequestById' : IDL.Func([IDL.Text], [IDL.Opt(Request)], ['query']),
    'getRequestsByCaller' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRequestStatus' : IDL.Func([IDL.Text, RequestStatus], [], []),
    'updateSparesUsed' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };